### ISSUE TITLE
[Question] - autoinstall not in repository

### ISSUE THREAD

**Issue by zhongliangong** [LTPV/LTPV#1]
I tried to download and install the repository according to the installation instructions, but was unable to locate the auto install script as given `chmod +x ./autoinstall && sudo ./autoinstall`. 

This should really be a question, but I can't find a way to label it.

Thanks for your help - I had, till now given up on profiling OpenCL on a current-gen CUDA-toolkit.

**Comment by sdenel** [comment]
You are right: this repo is a quick merge of two forks, with no installation files for Unix until now.

I just added back installation files for Unix:
- src/Makefile for compiling the library
- install/unix/autoinstall.sh to install the lib, the header and the ltpv python script

I can't test these files right now, so you may find problems using them. Don't hesitate to contact me by email, as it is necessary to have proper installation files again.

**Comment by ixeft** [comment]
Hello,
you can install LTPV using
./waf configure
./waf
sudo ./waf install
