### ISSUE TITLE
No firefox window

### ISSUE THREAD

**Issue by EvilPudding** [LTPV/LTPV#10]
Profiling happens, firefox window does not open, and if it's already open it does nothing.

There should be a separate command to visualize the xml, that way I could run it and know if it's working or not.

**Comment by salehjg** [comment]
you should edit your /usr/local/bin/ltpv, it tries to launch chromium, not firefox!
```
subprocess.Popen(['nohup', 'firefox', addr],
                 stdout=open('/dev/null', 'w'),
                 stderr=open('/dev/null', 'w'),
                 preexec_fn=os.setpgrp
                 )
```

Looks like readme file is not up to date

**Comment by EvilPudding** [comment]
Oh, the readme should probably say something about that.

**Comment by EvilPudding** [comment]
>Looks like readme file is not up to date

Oh, ok.
