### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pawanjoe** [LTPV/LTPV#7]
ltpv ./executable gives me an error  "ERROR: ld.so: object 'libltpv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored".

Please help. I have followed all steps of installation correctly.

**Comment by sdenel** [comment]
Hello pawanjoe,
Does libltpv.so exists? Have you read rights on it?

**Comment by ixeft** [comment]
Hello @pawanjoe ,

I pushed a modification that should solve your problem  648157a . feel free to reopen if the problem persist.

Regards,
FX
